vswh:
  # image:
  #   repository: 965232795465.dkr.ecr.cn-northwest-1.amazonaws.com.cn/github/bank-vaults/vault-secrets-webhook
  # vaultEnv:
  #   repository: 965232795465.dkr.ecr.cn-northwest-1.amazonaws.com.cn/github/bank-vaults/vault-env
  env:
    ENABLE_JSON_LOG: "true"
    LOG_LEVEL: warn
    VAULT_IMAGE: hashicorp/vault:1.14
    VAULT_LOG_LEVEL: warn
  certificate:
    useCertManager: true
    generate: false
  objectSelector:
    matchLabels:
      vault-injection: enabled
  # serviceAccount:
  #   annotations:
  #     eks.amazonaws.com/role-arn: arn:aws-cn:iam::965232795465:role/eks/irsa/vault-secrets-webhook
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 64m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 64Mi