vault:
  vaultContainerSpec:
    livenessProbe:
      httpGet:
        scheme: HTTP
        path: /v1/sys/health?standbyok=true
        port: 8200
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      httpGet:
        scheme: HTTP
        path: /v1/sys/health?standbyok=true&perfstandbyok=true&drsecondarycode=299
        port: 8200
      initialDelaySeconds: 5
      periodSeconds: 5
    startupProbe:
      httpGet:
        scheme: HTTP
        path: /v1/sys/init
        port: 8200
      periodSeconds: 10
      failureThreshold: 18
